# Generated by Django 6.1 on 2026-09-09 06:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('STAGIAIRE', 'Stagiaire'), ('RH', 'Ressources Humaines'), ('MAITRE_STAGE', 'Maître de Stage'), ('DIRECTEUR', 'Directeur de Service')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('lien', models.CharField(blank=True, help_text='Chemin relatif vers lequel rediriger au clic.', max_length=255)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProfilDirecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_directeur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('agence', models.CharField(blank=True, help_text='Ville / agence de rattachement.', max_length=150)),
                ('directeur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement', to='appStage.profildirecteur')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilMaitreStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(blank=True, max_length=150)),
                ('departement_affiliation', models.CharField(blank=True, help_text="Département d'appartenance du tuteur (informatif, distinct du département du stagiaire encadré).", max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_maitre_stage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_rh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(blank=True, max_length=150)),
                ('annee_etude', models.CharField(blank=True, choices=[('LICENCE_1', '1re année de Licence'), ('LICENCE_2', '2e année de Licence'), ('LICENCE_3', '3e année de Licence'), ('MASTER_1', '1re année de Master'), ('MASTER_2', '2e année de Master')], max_length=20)),
                ('etablissement', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_stagiaire', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format +226 suivi de 8 chiffres.', regex='^\\+226[0-9]{8}$')])),
                ('poste_souhaite', models.CharField(max_length=200)),
                ('filiere', models.CharField(blank=True, help_text='Transmise au profil du stagiaire si accepté.', max_length=150)),
                ('annee_etude', models.CharField(blank=True, choices=[('LICENCE_1', '1re année de Licence'), ('LICENCE_2', '2e année de Licence'), ('LICENCE_3', '3e année de Licence'), ('MASTER_1', '1re année de Master'), ('MASTER_2', '2e année de Master')], help_text="Année d'étude actuelle du candidat.", max_length=20)),
                ('cv', models.FileField(blank=True, null=True, upload_to='candidatures/cv/')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='candidatures/lm/')),
                ('piece_identite', models.FileField(blank=True, help_text='Copie de la CNIB (ou équivalent) du candidat.', null=True, upload_to='candidatures/cnib/')),
                ('avec_soutenance_souhaite', models.BooleanField(default=True, help_text="Préférence exprimée par le candidat, que le RH confirme ou ajuste à l'acceptation.")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('motif_refus', models.TextField(blank=True, help_text='Obligatoire côté formulaire si la candidature est refusée.')),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('departement_affecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures', to='appStage.departement')),
                ('departement_souhaite', models.ForeignKey(blank=True, help_text="Département choisi par le candidat, que le RH confirme ou ajuste à l'acceptation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_souhaitees', to='appStage.departement')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_traitees', to='appStage.profilrh')),
                ('stagiaire_cree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidature_origine', to='appStage.profilstagiaire')),
            ],
            options={
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_poste', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('A_VENIR', 'À venir'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('RESILIE', 'Résilié')], default='A_VENIR', max_length=20)),
                ('avec_soutenance', models.BooleanField(default=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='appStage.departement')),
                ('maitre_de_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages_encadres', to='appStage.profilmaitrestage')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='appStage.profilstagiaire')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='RapportHebdomadaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semaine', models.PositiveIntegerField()),
                ('contenu', models.TextField(blank=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('EN_RETARD', 'En retard')], default='EN_ATTENTE', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='appStage.stage')),
            ],
            options={
                'ordering': ['-numero_semaine'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('equipe', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('echeance', models.DateField(blank=True, null=True)),
                ('fichier', models.FileField(blank=True, help_text='Document de support ou consigne détaillée (optionnel).', null=True, upload_to='missions/')),
                ('statut', models.CharField(choices=[('A_FAIRE', 'À faire'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='A_FAIRE', max_length=20)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='appStage.stage')),
            ],
            options={
                'ordering': ['echeance'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evaluation', models.CharField(choices=[('MI_PARCOURS', 'Mi-parcours'), ('FINALE', 'Finale')], max_length=20)),
                ('note_technique', models.PositiveSmallIntegerField(default=10)),
                ('note_autonomie', models.PositiveSmallIntegerField(default=10)),
                ('note_communication', models.PositiveSmallIntegerField(default=10)),
                ('note_ponctualite', models.PositiveSmallIntegerField(default=10)),
                ('commentaire', models.TextField(blank=True)),
                ('date_evaluation', models.DateField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='appStage.stage')),
            ],
            options={
                'ordering': ['-date_evaluation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('compte_rendu', models.TextField(blank=True)),
                ('rh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entretiens_menes', to='appStage.profilrh')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='appStage.stage')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents_stage/')),
                ('type_document', models.CharField(choices=[('CONVENTION', 'Accord de stage'), ('CONTRAT', 'Contrat'), ('RAPPORT', 'Rapport'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15)),
                ('destinataire', models.CharField(choices=[('TUTEUR', 'Maître de stage'), ('RH', 'RH'), ('STAGIAIRE', 'Stagiaire')], default='TUTEUR', help_text='Qui doit voir/traiter ce document : le maître de stage, le RH, ou (documents émis par le RH, ex. contrat) le stagiaire lui-même.', max_length=15)),
                ('statut_signature', models.CharField(choices=[('NON_APPLICABLE', 'Non applicable'), ('EN_ATTENTE', 'En attente de signature'), ('SIGNE', 'Signé')], default='NON_APPLICABLE', max_length=20)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(blank=True, help_text='Mission à laquelle ce document se rapporte (livrable), le cas échéant.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='appStage.mission')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='appStage.stage')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='DemandeEncadrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('proposee_par', models.ForeignKey(blank=True, help_text="Directeur de service à l'origine de la proposition.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propositions_encadrement', to='appStage.profildirecteur')),
                ('maitre_de_stage_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to='appStage.profilmaitrestage')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_encadrement', to='appStage.stage')),
            ],
            options={
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('justifie', models.BooleanField(default=False)),
                ('note_activite', models.CharField(blank=True, help_text='Courte description de ce qui a été fait ce jour-là, saisie par le stagiaire au moment de pointer.', max_length=280)),
                ('valide_par_tuteur', models.BooleanField(default=False, help_text='Auto-déclarée par le stagiaire, puis confirmée par le maître de stage.')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='appStage.stage')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stage', 'date')},
            },
        ),
    ]
