# Generated by Django 6.1 on 2026-09-14 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeencadrement',
            name='motif_refus',
            field=models.TextField(blank=True, help_text='Renseigné par le maître de stage en cas de refus ; visible uniquement par le directeur.'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='departement',
            field=models.ForeignKey(blank=True, help_text="Laissé vide tant que le stagiaire n'a pas encore été affecté à un service (voir la page Affectation).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='appStage.departement'),
        ),
    ]
