# Generated by Django 6.1 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStage', '0002_alter_evaluation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentstage',
            name='destinataire',
            field=models.CharField(
                choices=[
                    ('TUTEUR', 'Maître de stage'),
                    ('RH', 'RH'),
                    ('STAGIAIRE', 'Stagiaire'),
                ],
                default='TUTEUR',
                help_text=(
                    "Qui doit voir/traiter ce document : le maître de stage, le RH, ou "
                    "(documents émis par le RH, ex. contrat) le stagiaire lui-même."
                ),
                max_length=15,
            ),
        ),
    ]
