# Generated by Django 6.1 on 2026-08-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStage', '0003_documentstage_destinataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstage',
            name='type_document',
            field=models.CharField(choices=[('CONVENTION', 'Accord de stage'), ('CONTRAT', 'Contrat'), ('RAPPORT', 'Rapport'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15),
        ),
    ]
