# Generated by Django 6.1 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStage', '0004_alter_documentstage_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='filiere',
            field=models.CharField(blank=True, help_text="Transmise au profil du stagiaire si accepté.", max_length=150),
        ),
        migrations.AddField(
            model_name='candidature',
            name='annee_etude',
            field=models.CharField(blank=True, help_text="Ex : « 3ème Année ».", max_length=50),
        ),
    ]
