# Generated by Django 6.1 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStage', '0005_candidature_filiere_annee_etude'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='note_activite',
            field=models.CharField(
                blank=True, max_length=280,
                help_text="Courte description de ce qui a été fait ce jour-là, saisie par le stagiaire au moment de pointer.",
            ),
        ),
    ]
