# Generated by Django 6.1 on 2026-09-02 09:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStage', '0005_candidature_filiere_annee_etude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='annee_etude',
            field=models.CharField(blank=True, choices=[('LICENCE_1', '1re année de Licence'), ('LICENCE_2', '2e année de Licence'), ('LICENCE_3', '3e année de Licence'), ('MASTER_1', '1re année de Master'), ('MASTER_2', '2e année de Master')], help_text="Année d'étude actuelle du candidat.", max_length=20),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='avec_soutenance_souhaite',
            field=models.BooleanField(default=True, help_text="Préférence exprimée par le candidat, que le RH confirme ou ajuste à l'acceptation."),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='departement_souhaite',
            field=models.ForeignKey(blank=True, help_text="Département choisi par le candidat, que le RH confirme ou ajuste à l'acceptation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_souhaitees', to='appStage.departement'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format +226 suivi de 8 chiffres.', regex='^\\+226[0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='profilstagiaire',
            name='annee_etude',
            field=models.CharField(blank=True, choices=[('LICENCE_1', '1re année de Licence'), ('LICENCE_2', '2e année de Licence'), ('LICENCE_3', '3e année de Licence'), ('MASTER_1', '1re année de Master'), ('MASTER_2', '2e année de Master')], max_length=20),
        ),
    ]
